# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 8.12  # 465 deg/s in rad/s
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 8.12  # 465 deg/s in rad/s
    has_acceleration_limits: true
    max_acceleration: 50.0
  joint_3:
    has_velocity_limits: true
    max_velocity: 9.16  # 525 deg/s in rad/s
    has_acceleration_limits: true
    max_acceleration: 50.0
  joint_4:
    has_velocity_limits: true
    max_velocity: 9.86  # 565 deg/s in rad/s
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_5:
    has_velocity_limits: true
    max_velocity: 9.86  # 565 deg/s in rad/s
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_6:
    has_velocity_limits: true
    max_velocity: 17.45  # 1000 deg/s in rad/s
    has_acceleration_limits: true
    max_acceleration: 5.0