# moveit_controllers_sim.yaml

trajectory_execution:
  allowed_execution_duration_scaling: 10.0
  allowed_goal_duration_margin: 10.0
  allowed_start_tolerance: 0.1
  trajectory_duration_monitoring: false

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: "follow_joint_trajectory"
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
