# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    follow_joint_trajectory:
      type: joint_trajectory_controller/JointTrajectoryController

follow_joint_trajectory:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    
    command_interfaces:
      - position
      - velocity
    
    state_interfaces:
      - position
      - velocity
    
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
