# worm_picker_parameters.yaml
# 
# Copyright (c) 2024
# SPDX-License-Identifier: Apache-2.0

parameters:
  config_files:
    workstation: "/config/parameters/workstation_data.json"
    hotel: "/config/parameters/hotel_data.json"
    stages: "/config/parameters/defined_stages.json"
    tasks: "/config/parameters/defined_tasks.json"
    timer_log: "/worm-picker/worm_picker_core/config/logs"

  actions:
    exec_task: "/execute_task_solution"
    task_command: "/task_command"

  operation_modes:
    group: "gp4_arm"
    plate: "plateMode"
    worm: "wormMode"

  end_effectors:
    current_factor: "eoat_tcp"
    plate_factor: "eoat_tcp"
    worm_factor: "wormpick_tcp"

  settings:
    server_timeout: 3
    max_retries: 10
    planning_attempts: 5

  validation:
    pos_tol: 0.01
    ori_tol: 0.01
    joint_tol: 0.01
    step_size: 0.01
    min_fraction: 0.9